package com.zhou4h.springboot3.common;

import com.fasterxml.jackson.databind.ObjectMapper;

import java.util.List;
import java.util.regex.Pattern;

public class JiraDataToMarkdownConstants {

    public static final String EMPTY = "";
    public static final String NEW_LINE = "\n";
    public static final String DOUBLE_NEW_LINE = "\n\n";
    public static final String SINGLE_SPACE = " ";
    public static final String HORIZONTAL_RULE = "---";
    public static final String FIRST_LEVEL_HEADING = "# ";
    public static final String SECOND_LEVEL_HEADING = "## ";
    public static final String LIST_ITEM_PREFIX = "- ";
    public static final String LIST_ITEM_LABEL_PREFIX = "- Item ";
    public static final String LABEL_SEPARATOR = ": ";
    public static final String KEY_VALUE_SEPARATOR = "=";
    public static final String COMMA_SEPARATOR = ", ";
    public static final String PIPE_SEPARATOR = " | ";
    public static final String SLASH = "/";
    public static final String OPEN_PAREN_PREFIX = " (";
    public static final String CLOSE_PAREN = ")";
    public static final String AUTHOR_PREFIX = " by ";
    public static final String CREATED_PREFIX = " on ";
    public static final String SECONDS_SUFFIX = "seconds";
    public static final String HTML_BREAK_TOKEN = "__JIRA_MD_BREAK__";
    public static final String DEFAULT_API_VERSION = "2";
    public static final String JSON_MEDIA_TYPE = "application/json";
    public static final String HEADER_AUTHORIZATION = "Authorization";
    public static final String HEADER_ACCEPT = "Accept";
    public static final String HEADER_CONTENT_TYPE = "Content-Type";
    public static final String OPERATION_PARSE_JIRA_RESPONSE = "Parse Jira response body";
    public static final String OPERATION_LOAD_JIRA_FIELD_METADATA = "Load Jira field metadata";
    public static final String SEARCH_EMPTY_DOCUMENT_TITLE = "# Jira Issues";
    public static final String SEARCH_EMPTY_DOCUMENT_BODY = "No issues found.";
    public static final String ISSUE_DOCUMENT_TITLE_PREFIX = "Jira IssueID: ";
    public static final String GENERIC_RESPONSE_TITLE = "# Jira Response";
    public static final String EMPTY_RESPONSE_BODY = "The response body is empty.";
    public static final String SECTION_LABEL_FIELDS = "Fields";
    public static final String SECTION_LABEL_COMMENT_PREFIX = "Comment ";
    public static final String SECTION_LABEL_WORKLOG_PREFIX = "Worklog ";
    public static final String JSON_KEY_ACCOUNT_ID = "accountId";
    public static final String JSON_KEY_EMAIL_ADDRESS = "emailAddress";
    public static final String JSON_KEY_FILENAME = "filename";
    public static final String JSON_KEY_CHILD = "child";
    public static final String JSON_KEY_ID = "id";
    public static final String JSON_KEY_KEY = "key";
    public static final String JSON_KEY_NAME = "name";
    public static final String JSON_KEY_NAMES = "names";
    public static final String JSON_KEY_TYPE = "type";
    public static final String JSON_KEY_VALUE = "value";
    public static final String JSON_KEY_ISSUES = "issues";
    public static final String JSON_KEY_FIELDS = "fields";
    public static final String JSON_KEY_TOTAL = "total";
    public static final String JSON_KEY_SCHEMA = "schema";
    public static final String JSON_KEY_SUMMARY = "summary";
    public static final String JSON_KEY_RENDERED_FIELDS = "renderedFields";
    public static final String JSON_KEY_DISPLAY_NAME = "displayName";
    public static final String JSON_KEY_CACHED_VALUE = "cachedValue";
    public static final String JSON_KEY_PROGRESS = "progress";
    public static final String JSON_KEY_VOTES = "votes";
    public static final String JSON_KEY_DEVELOPMENT = "development";
    public static final String JSON_KEY_ISSUETYPE = "issuetype";
    public static final String JSON_KEY_STATUS = "status";
    public static final String JSON_KEY_PRIORITY = "priority";
    public static final String JSON_KEY_ASSIGNEE = "assignee";
    public static final String JSON_KEY_AUTHOR = "author";
    public static final String JSON_KEY_CREATED = "created";
    public static final String JSON_KEY_BODY = "body";
    public static final String JSON_KEY_COMMENT = "comment";
    public static final String JSON_KEY_COMMENTS = "comments";
    public static final String JSON_KEY_RENDERED_BODY = "renderedBody";
    public static final String JSON_KEY_WORKLOGS = "worklogs";
    public static final String JSON_KEY_MIME_TYPE = "mimeType";
    public static final String JSON_KEY_SIZE = "size";
    public static final String JSON_KEY_CONTENT = "content";
    public static final String JSON_KEY_SELF = "self";
    public static final String JSON_KEY_EXPAND = "expand";
    public static final String JSON_KEY_OUTWARD = "outward";
    public static final String JSON_KEY_INWARD = "inward";
    public static final String JSON_KEY_OUTWARD_ISSUE = "outwardIssue";
    public static final String JSON_KEY_INWARD_ISSUE = "inwardIssue";
    public static final String JSON_KEY_HAS_VOTED = "hasVoted";
    public static final String JSON_KEY_WATCH_COUNT = "watchCount";
    public static final String JSON_KEY_IS_WATCHING = "isWatching";
    public static final String JSON_KEY_OVERALL = "overall";
    public static final String JSON_KEY_ITEMS = "items";
    public static final String JSON_KEY_SYSTEM = "system";
    public static final String FIELD_TYPE_STRING = "string";
    public static final String FIELD_TYPE_DATE = "date";
    public static final String FIELD_TYPE_DATETIME = "datetime";
    public static final String FIELD_TYPE_NUMBER = "number";
    public static final String FIELD_TYPE_USER = "user";
    public static final String FIELD_TYPE_ISSUE = "issue";
    public static final String FIELD_TYPE_ISSUETYPE = "issuetype";
    public static final String FIELD_TYPE_PROJECT = "project";
    public static final String FIELD_TYPE_STATUS = "status";
    public static final String FIELD_TYPE_PRIORITY = "priority";
    public static final String FIELD_TYPE_RESOLUTION = "resolution";
    public static final String FIELD_TYPE_COMPONENT = "component";
    public static final String FIELD_TYPE_VERSION = "version";
    public static final String FIELD_TYPE_SECURITY_LEVEL = "securitylevel";
    public static final String FIELD_TYPE_GROUP = "group";
    public static final String FIELD_TYPE_PROJECT_CATEGORY = "projectcategory";
    public static final String FIELD_TYPE_OPTION = "option";
    public static final String FIELD_TYPE_OPTION_WITH_CHILD = "option-with-child";
    public static final String FIELD_TYPE_ATTACHMENT = "attachment";
    public static final String FIELD_TYPE_ISSUE_LINK = "issuelink";
    public static final String FIELD_TYPE_ISSUE_LINKS = "issuelinks";
    public static final String FIELD_TYPE_COMMENTS_PAGE = "comments-page";
    public static final String FIELD_TYPE_TIME_TRACKING = "timetracking";
    public static final String FIELD_TYPE_VOTES = "votes";
    public static final String FIELD_TYPE_WATCHES = "watches";
    public static final String FIELD_TYPE_PROGRESS = "progress";
    public static final String FIELD_TYPE_WORKLOG = "worklog";
    public static final String FIELD_TYPE_ARRAY = "array";
    public static final String FIELD_VALUE_TIME_SPENT = "timeSpent";
    public static final String FIELD_VALUE_ORIGINAL_ESTIMATE = "originalEstimate";
    public static final String FIELD_VALUE_REMAINING_ESTIMATE = "remainingEstimate";
    public static final String JSON_KEY_TIME_SPENT_SECONDS = "timeSpentSeconds";
    public static final String JSON_KEY_ORIGINAL_ESTIMATE_SECONDS = "originalEstimateSeconds";
    public static final String JSON_KEY_REMAINING_ESTIMATE_SECONDS = "remainingEstimateSeconds";
    public static final String NORMALIZED_LINKED_ISSUES = "linkedissues";
    public static final String FIELD_ID_SUBTASKS = "subtasks";
    public static final String SECTION_LABEL_SUMMARY_SOURCE = "Summary";
    public static final String SECTION_LABEL_SUMMARY = "Summary(Title)";
    public static final String SECTION_LABEL_LINKED_ISSUES = "Linked Issues";
    public static final String SECTION_LABEL_ISSUE_LINKS_ALIAS = "Issuelinks";
    public static final String SECTION_LABEL_ISSUE_LINKS = "Issue Links";
    public static final String SECTION_LABEL_SUB_TASKS_ALIAS = "Sub Tasks";
    public static final String SECTION_LABEL_SUBTASKS = "Subtasks";
    public static final String SECTION_LABEL_SUB_TASKS = "Sub-Tasks";
    public static final String REST_API_PATH = "/rest/api/";
    public static final String FIELD_CATALOG_PATH = "/field";
    public static final String EMAIL_VALUE_PREFIX = "email=";
    public static final String CHILD_VALUE_PREFIX = ", child=";
    public static final String DEVELOPMENT_EMBEDDED_JSON_MARKER = "devSummaryJson=";
    public static final String DEVELOPMENT_ARRAY_PREFIX = "=[";
    public static final String DEVELOPMENT_ARRAY_SUFFIX = "]";
    public static final String DEVELOPMENT_PATH_SEPARATOR = ".";
    public static final String UNKNOWN_ISSUE_IDENTIFIER = "Unknown";
    public static final String HTML_NON_BREAKING_SPACE = "&nbsp;";
    public static final int HTTP_SUCCESS_MIN = 200;
    public static final int HTTP_SUCCESS_MAX = 299;
    public static final int RESPONSE_BODY_PREVIEW_LENGTH = 400;
    public static final ObjectMapper OBJECT_MAPPER = new ObjectMapper();
    public static final List<String> DEVELOPMENT_SUMMARY_KEYS = List.of(
            "pullrequest",
            "build",
            "review",
            "deployment-environment",
            "repository",
            "branch"
    );
    public static final Pattern TRAILING_SLASHES = Pattern.compile("/+$");
    public static final Pattern API_VERSION_PREFIX = Pattern.compile("^/?(?:rest/)?api/");
    public static final Pattern EDGE_SLASHES = Pattern.compile("^/+|/+$");
    public static final Pattern NORMALIZE_KEY = Pattern.compile("[^a-z0-9]");
    public static final Pattern HTML_BREAK = Pattern.compile("(?i)<br\\s*/?>");
    public static final Pattern HTML_LIST_OPEN = Pattern.compile("(?i)<li[^>]*>");
    public static final Pattern HTML_LIST_CLOSE = Pattern.compile("(?i)</li>");
    public static final Pattern HTML_PARAGRAPH_CLOSE = Pattern.compile("(?i)</p>");
    public static final Pattern HTML_DIV_CLOSE = Pattern.compile("(?i)</div>");
    public static final Pattern HTML_HEADING_CLOSE = Pattern.compile("(?i)</h[1-6]>");
    public static final Pattern SPACE_AROUND_NEW_LINE = Pattern.compile("[ \\t]*\\n[ \\t]*");
    public static final Pattern MORE_THAN_TWO_NEW_LINES = Pattern.compile("\\n{3,}");
    public static final Pattern CAMEL_CASE_BOUNDARY = Pattern.compile("([a-z0-9])([A-Z])");
    public static final String CAMEL_CASE_BOUNDARY_REPLACEMENT = "$1 $2";

}
